version: "3.8"
services:
  # Create frontend container
  web: # Name of our service
    build: ./ # path to dockerfile
    ports: # Port binding to host from docker container
      - "5173:5173"
      - "3200:3200"
    container_name: web-docker
    restart: always # What to do if container crashes
    links:
      - db
  # Create backend container
  db:
    # specify the image here
    image: postgis/postgis
    container_name: db
    # uncomment if you want to build the image yourself
    # build: .
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=osm_docker
      - POSTGRES_USER=postgresdocker
    restart: always
