name: Format

on:
  push:
    branches:
      - main
      - recreate-previous-page-backend-functionality
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: yarn format --list-different
